theme: jekyll-theme-merlot
title                    : "Cufy"

name                     : &name "Cufy"
description              : &description "Cufy Official"
url                      : https://cufy.github.io

repository               : "lsafer/cufy.github.io"
teaser                   : "cufy.logo.png"

comments:

og_image                 :  "cufy.logo.png"
author:
  name             : "LSafer"
  avatar           : "lsafer.logo.png"
  bio              : "Sulaiman Obody"
  email            : "lsaferse@gmail.com"
  github           : "lsafer"
